version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - ${ENV_FILE:-.env}  # Se usará el archivo .env por defecto
    networks:
      - laravel
    depends_on:
      - mysql
      - redis
    

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:7/oGbYPJfRr2UN/xP9I/W79XmdTqIDD9LAWlrBibVjY=
      - DB_CONNECTION=mysql
      - DB_HOST=mysql          # Cambia 'localhost' por 'mysql'
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
